### PR TITLE
fix: UNFIX ALL DA HYPALINKS

### PR DESCRIPTION
**Pull request by xrowii**

### CODE REVIEW

**Review by PorridgePi — CHANGES_REQUESTED** [review]
You have un-fixed the hyperlinks.

**Comment by xrowii** [comment]
???? ISNT THAT WHAT I SAID THIS DOES

**Comment by xrowii** [comment]
ISNT THAT WHAT THIS IS SUPPOSED TO DO

**Comment by PorridgePi** [comment]
Thank you for your help.

**Review by xrowii — COMMENTED** [review]
very good!

**Pull request closed without merging**
